"""create email_messages table

Revision ID: 91f43519dc33
Revises: 
Create Date: 2025-11-17 19:41:46.235729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f43519dc33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawals_id'), table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_index(op.f('ix_airtimes_id'), table_name='airtimes')
    op.drop_table('airtimes')
    op.drop_index(op.f('ix_Deposit_id'), table_name='Deposit')
    op.drop_table('Deposit')
    op.drop_index(op.f('ix_email_messages_gmail_account'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_parsed_transaction_id'), table_name='email_messages')
    op.drop_table('email_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gmail_account', sa.VARCHAR(), nullable=True),
    sa.Column('message_id', sa.VARCHAR(), nullable=True),
    sa.Column('subject', sa.VARCHAR(), nullable=True),
    sa.Column('sender', sa.VARCHAR(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('received_at', sa.DATETIME(), nullable=True),
    sa.Column('parsed_transaction_id', sa.VARCHAR(), nullable=True),
    sa.Column('matched', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_messages_parsed_transaction_id'), 'email_messages', ['parsed_transaction_id'], unique=False)
    op.create_index(op.f('ix_email_messages_message_id'), 'email_messages', ['message_id'], unique=1)
    op.create_index(op.f('ix_email_messages_id'), 'email_messages', ['id'], unique=False)
    op.create_index(op.f('ix_email_messages_gmail_account'), 'email_messages', ['gmail_account'], unique=False)
    op.create_table('Deposit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipient', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('gateway_response', sa.TEXT(), nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('sim_used', sa.VARCHAR(length=20), nullable=True),
    sa.Column('service_partner_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('partner_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('validated_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Deposit_id'), 'Deposit', ['id'], unique=False)
    op.create_table('airtimes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipient', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('ussd_code', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('gateway_response', sa.TEXT(), nullable=True),
    sa.Column('sim_used', sa.VARCHAR(length=20), nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('service_partner_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('partner_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('validated_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airtimes_id'), 'airtimes', ['id'], unique=False)
    op.create_table('withdrawals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('sender', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ussd_code', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('gateway_response', sa.TEXT(), nullable=True),
    sa.Column('sim_used', sa.VARCHAR(length=20), nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('service_partner_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('partner_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('validated_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawals_id'), 'withdrawals', ['id'], unique=False)
    # ### end Alembic commands ###
